### ISSUE TITLE
sys.executable is empty when running jython-standalone-2.7.0.jar

### ISSUE THREAD

**Issue by tvpadmanabhan** [jython/jython#315]
Hi all,

I am unable to execute the following command"
[java](http://www.javaranch.com/) -jar ~/.m2/repository/org/python/jython-standalone/2.7.0/jython-standalone-2.7.0.jar -m ensurepip

I get the following stack trace. Can anyone please guide me as to what is the issue and how to solve it?

Traceback (most recent call last):
```
 File "/Users/***/.m2/repository/org/python/jython-standalone/2.7.0/jython-standalone-2.7.0.jar/Lib/runpy.py", line 161, in _run_module_as_main
 File "/Users/***/.m2/repository/org/python/jython-standalone/2.7.0/jython-standalone-2.7.0.jar/Lib/runpy.py", line 72, in _run_code
 File "/Users/***/.m2/repository/org/python/jython-standalone/2.7.0/jython-standalone-2.7.0.jar/Lib/ensurepip/__main__.py", line 4, in <module>
 File "/Users/***/.m2/repository/org/python/jython-standalone/2.7.0/jython-standalone-2.7.0.jar/Lib/ensurepip/__init__.py", line 220, in _main
 File "/Users/***/.m2/repository/org/python/jython-standalone/2.7.0/jython-standalone-2.7.0.jar/Lib/ensurepip/__init__.py", line 123, in bootstrap
 File "/Users/***/.m2/repository/org/python/jython-standalone/2.7.0/jython-standalone-2.7.0.jar/Lib/ensurepip/__init__.py", line 45, in _run_pip
 File "/var/folders/96/llwnx0n57vd17gtfyw124z500000gq/T/tmpARwn47/pip-1.6-py2.py3-none-any.whl/pip/__init__.py", line 10, in <module>
 File "/var/folders/96/llwnx0n57vd17gtfyw124z500000gq/T/tmpARwn47/pip-1.6-py2.py3-none-any.whl/pip/util.py", line 13, in <module>
 File "/var/folders/96/llwnx0n57vd17gtfyw124z500000gq/T/tmpARwn47/pip-1.6-py2.py3-none-any.whl/pip/backwardcompat/__init__.py", line 115, in <module>
 File "/Users/***/.m2/repository/org/python/jython-standalone/2.7.0/jython-standalone-2.7.0.jar/Lib/distutils/sysconfig.py", line 28, in <module>
 File "/Users/***/.m2/repository/org/python/jython-standalone/2.7.0/jython-standalone-2.7.0.jar/Lib/posixpath.py", line 367, in realpath
 File "/Users/***/.m2/repository/org/python/jython-standalone/2.7.0/jython-standalone-2.7.0.jar/Lib/posixpath.py", line 373, in _joinrealpath
 **File "/Users/***/.m2/repository/org/python/jython-standalone/2.7.0/jython-standalone-2.7.0.jar/Lib/posixpath.py", line 61, in isabs
AttributeError: 'NoneType' object has no attribute 'startswith**'

```
Thanks and regards,
Paddy

Tried searching for this specific error and got [url]this post[https://stackoverflow.com/questions/59284551/jython-unable-to-install-ensurepip] as the first search result but it didn't help me.

**Comment by Stewori** [comment]
It would be good if you could check if the issue still occurs with latest release 2.7.3 and even better check with current master.

**Comment by tvpadmanabhan** [comment]
Thanks a lot, @Stewori , it is working with a 2.7.3 jar.

**Comment by Stewori** [comment]
Ah, that's good to hear. Then I'll close this. Stay tuned for 2.7.4, which will be release in Q2 this year.
